spring:
  application:
    #\u670D\u52A1\u540D
    name: service-01

server:
  #\u670D\u52A1\u7AEF\u53E3
  port: 8003

eureka:
  instance:
    #eureka\u4E3B\u673A\u540D\uFF0C\u4F1A\u5728\u63A7\u5236\u9875\u9762\u4E2D\u663E\u793A
    hostname: localhost
    #eureka\u670D\u52A1\u5668\u9875\u9762\u4E2Dstatus\u7684\u8BF7\u6C42\u8DEF\u5F84
    status-page-url: http://${eureka.instance.hostname}:${server.port}/index
  client:
    serviceUrl:
      #\u5728\u6CE8\u518C\u4E2D\u5FC3\u4E2D\u8FDB\u884C\u6CE8\u518C
      defaultZone: http://localhost:8001/eureka/
